### ISSUE TITLE
lab/memory-gdb: Fix `assert`s that compare pointers instead of data

### ISSUE THREAD

**Issue by teodutu** [systems-cs-pub-ro/iocla#121]
[These `assert`s](https://github.com/systems-cs-pub-ro/iocla/blob/56d3dccb47fea0f801281462b54e65aa0a944b08/laborator/content/operatii-memorie-gdb/7-pointers/pointers.c#L26-L28) only compare pointers to the returned arrays and not the data inside them. This is incorrect. They should be fixed to iterate the arrays and compare each element individually.

**Comment by RCX777** [comment]
`strcpy` in assert call needs to be changed to `my_strcpy`
