### ISSUE TITLE
lab/c-assembly: Add some linking exercises

### ISSUE THREAD

**Issue by teodutu** [systems-cs-pub-ro/iocla#132]
The [C-Assembly lab](https://github.com/systems-cs-pub-ro/iocla/tree/master/laborator/content/interactiune-c-assembly) is lacking in content. We should update it with some linking exercises, as they fit quite well here since this lab is mostly about the interaction between object files, i.e. linking. The [exercises to be removed from the Compilation lab](https://github.com/systems-cs-pub-ro/iocla/issues/126) are good candidates to be introduced here, as well as some exercises from the [old linking lab](https://github.com/systems-cs-pub-ro/iocla/tree/lab-linking/laborator/lab-12).

**Comment by Dave080302** [comment]
This PR https://github.com/systems-cs-pub-ro/iocla/pull/166 should fix the issue
