### ISSUE TITLE
Unclear use of "(void)" in labs

### ISSUE THREAD

**Issue by raresdb** [systems-cs-pub-ro/iocla#148]
An explanation about the use of (void) in code should be added to the labs so that the students will know what to do with that.
Ideas: An explanation added to the lab theory and some comments in the code. More than that, the students can be encouraged to try to compile the code without the use of the "(void)" to see the behaviour of the compiler in that situation.

**Comment by dbaluta** [comment]
Cred ca e suficient sa le spunem sa scoata `(void)`, sa recompileze si sa observe rezultatele.
