### ISSUE TITLE
New versions of Ghidra - steps not present in the lab

### ISSUE THREAD

**Issue by raresdb** [systems-cs-pub-ro/iocla#165]
For newer versions of Ghidra, when the user wants to add an executable, a window appears where it is required to add some infos about the type of the file. The default configurations are not always the best for reverse engineering that executable, and they differ from platform to platform. Some steps about this config should be added to the laboratory where Ghidra is introduced.

**Comment by darius-m** [comment]
Unfortunately, updating the information in the lab probably only makes sense if the VM / container used for the labs / homework also uses that version of application. While I agree that having instructions for a newer version of Ghidra may be useful, there simply isn't a good way to maintain instruction sets for multiple versions of the tool without making the document really confusing. The instructions will be updated when a new version of the VM (or maybe a container) is created, but until then you will likely have to either use the older version (from the VM, that is also presented in the lab), or read the official documentation.

**Comment by teodutu** [comment]
I have checked Ghidra 10.2.3 and the default config works just fine on my native Linux Mint 21.1. @raresdb can you provide the OS + Ghidra version to reproduce this?

**Comment by raresdb** [comment]
It also works well on my system - Ubuntu Linux 22.04, with the same version of Ghidra as you @teodutu. When I asked the students who had this problem last time, none responded, therefore I cannot give an exact version where it didn't work. I will assume that the issue with the wrong configuration appears only in some particular cases.

**Comment by raresdb** [comment]
It is also possible that the issue may appear on windows systems, although I haven't tried it, since I remember some of them were using wsl for the labs.

**Comment by gabrielmocanu** [comment]
Mark as fixed, not reproducible.
