### ISSUE TITLE
[BUG] Makefile not compiling source code on M1 CPU

### ISSUE THREAD

**Issue by whitewolf31** [systems-cs-pub-ro/iocla#46]
`gcc -Wall -Wextra -Werror -m32 -c mirror.c -o mirror.o`
`gcc -Wall -Wextra -Werror -m32 mirror.o -o mirror`
`ld: unknown/unsupported architecture name for: -arch armv4t`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: *** [mirror] Error 1`

Potential fix:

Removing -m32 argument

**Comment by doringeman** [comment]
My advice is to use the IOCLA Virtual Machine.
In order to get it working on an M1 CPU, follow the next steps:
- download the VM in the [`ova`](https://repository.grid.pub.ro/cs/iocla/vm/) format
- convert it to [`qcow2`](https://www.tekbyte.net/how-to-convert-ova-image-to-qcow2-qemu-and-virt-manager/)
- use UTM as described in this [tutorial](https://ocw.cs.pub.ro/courses/uso/resurse/mv)

**Comment by gabrielmocanu** [comment]
@whitewolf31 

Do you fix this problem? Can we close this BUG?

**Comment by whitewolf31** [comment]
I didn't manage to run the IOCLA Virtual Machine on UTM without having extreme lag, therefore making it unusable. There might be a way to run it using Parallels, but you have to pay for it<br/>
However there is a way to compile programs on M1 for x86_64 and run them using Rosetta emulator (which is actually really good)<br/>
Click this [Github Link](https://gist.github.com/progrium/b286cd8c82ce0825b2eb3b0b3a0720a0) for more info<br/>

In order to install packages for x86_64 architecture you must first install brew for x86_64<br/>
`$ arch -x86_64 zsh # emulate zsh terminal on x86_64 architecture`
`% /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" # install homebrew for x86_64`<br/>
We have just installed homebrew for x86_64 architecture. In order to install gcc compiler for x86_64 you should run the following command:<br/>
`$ arch -x86_64 brew install gcc`<br/>
If you are in the previous zsh terminal, you can forget the `arch -x86-64`<br/>
In order to compile, run the usual gcc command, by adding `arch -x86_64` at the beginning.<br/>
In order to check if the program has been compiled for x86_64 run `file <name_of_program>`.

**Comment by gabrielmocanu** [comment]
@whitewolf31 

Thanks for the update and for all the information.
