### ISSUE TITLE
Add common Makefile for all demos and exercises

### ISSUE THREAD

**Issue by razvand** [systems-cs-pub-ro/iocla#81]
Currently each demo or exercise folder in the repository is using its own Makefile. Even though the build rules should be the same, there are inconsistencies among them.

I propose we use a common Makefile and include that in the demo/exercise Makefile, minimizing the Makefiles and making them consistent.

We could create a Makefile-to-be-included for C files (similar to [this one](https://github.com/razvand/snippets/blob/master/basic/c/common.mk)) and one for assembly files (similar to [this one](https://github.com/razvand/snippets/blob/master/basic/asm/common.mk)).

**Comment by gabrielmocanu** [comment]
Definitely agree.

**Comment by RazvanN7** [comment]
Makes sense. I'm on board.

**Comment by darius-m** [comment]
Created PR #89 for this issue. All labs must be updated before merging, however.

**Comment by darius-m** [comment]
Completed through #89, #90, #95, #103.
