### ISSUE TITLE
Define and use coding style throughout demos and exercises

### ISSUE THREAD

**Issue by razvand** [systems-cs-pub-ro/iocla#82]
Currently there are coding style inconsistencies among source code files for demos and exercises.

I propose we define and use a simple coding style for C and assembly source code. I suggest we used [the Linux kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html). We could then use [checkpatch](https://www.kernel.org/doc/html/latest/dev-tools/checkpatch.html) to quickly validate compliance of C source code style.

**Comment by gabrielmocanu** [comment]
@razvand 

We should add also this rule for all PRs. [1]

[1]: https://github.com/marketplace/actions/checkpatch-pl-pr-review

**Comment by teodutu** [comment]
> We should add also [this](https://github.com/marketplace/actions/checkpatch-pl-pr-review) rule for all PRs.

I made [this test PR](https://github.com/teodutu/test-github-actions/pull/1) to get used to github actions and to the `checkpatch.pl` action itself. I quite like the fact that it outputs errors as review comments. I think it's what we need.

Are there any errors you think we should skip? Maybe `Missing or malformed SPDX-License-Identifier tag`? Or should we go with the full [Linux kernel coding style](https://www.kernel.org/doc/html/latest/process/coding-style.html?highlight=coding%20style)?

**Comment by dbaluta** [comment]
Let's go full Linux kernel coding style.

**Comment by gabrielmocanu** [comment]
Please check [this PR] to include github workflow for checkpatch. I will make a PR also for the private repository.

[this PR]: https://github.com/systems-cs-pub-ro/iocla/pull/83

**Comment by razvand** [comment]
@gabrielmocanu , I merged the two PRs.

Still we should add a CONTRIBUTING.md document that details the coding style to use and best practices when submitting code.

**Comment by teodutu** [comment]
We also need to choose a license so we can add the SPDX identifiers.

**Comment by razvand** [comment]
@teodutu , I opened up issue #84 to discuss about the license to use.
